In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam'] = df.Category.apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[0:4]

680     Missed your call cause I was yelling at scrapp...
1436                                Dad went out oredi...
3900    Ü mean it's confirmed... I tot they juz say on...
2181    Babe ! How goes that day ? What are you doing ...
Name: Message, dtype: object

In [16]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[0:4]

680     0
1436    0
3900    0
2181    0
Name: spam, dtype: int64

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7723 sparse matrix of type '<class 'numpy.int64'>'
	with 59507 stored elements in Compressed Sparse Row format>

In [20]:
X_train_cv.toarray()[0:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
X_train_cv.shape

(4457, 7723)

In [39]:
v.get_feature_names_out()[1591]

'call'

In [ ]:
v.vocabulary_

In [26]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
np.where(X_train_np[0] != 0)

(array([1102, 1591, 1615, 1676, 1898, 2923, 3441, 4148, 4472, 4474, 5934,
        6273, 6919, 6925, 7337, 7372, 7663, 7689]),)

In [30]:
X_train[:4][680]

"Missed your call cause I was yelling at scrappy. Miss u. Can't wait for u to come home. I'm so lonely today."

In [36]:
X_train_np[0][1102]

1

In [40]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [41]:
X_test_cv = v.transform(X_test)

In [42]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       960
           1       0.97      0.94      0.95       155

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [45]:
emails = [
    "Hey mohan, can we get together to watch footbal game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [48]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [49]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [50]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       960
           1       0.97      0.94      0.95       155

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

